<?php echo $this->getContent() ?>
<?php
echo $this->tag->form(
    array(
        "index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "roomtypeform",
        "method" => "get"
    )
);
?>
<section class="content-header">
    <h2>
        Danh sách phòng
    </h2>
    <div class="arrange-button">
        <a href="/backend/roomtype/new/" class="btn btn-info" id="modaltrigger" rel="leanModal">Thêm mới</a>
    </div>
</section>
<section class="content">
    <div class="sidebar-form">
        <div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Tên phòng"
                           value="<?php echo $data['filter'] ?>">
                        <span class="input-group-btn">
                            <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                            </button>
                        </span>
                </div>
            </div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Danh mục bài viết</span>
                    <select class="form-control" id="idlang" name="idlang">
                        <option value="" selected>Tất cả</option>
                        <?php foreach ($data["langs"] as $items): ?>
                            <?php if ($items->id == $data['idlang'])
                                echo "<option value=\"$items->id\" selected>$items->lang</option>";
                            else
                                echo "<option value=\"$items->id\">$items->lang</option>";
                            ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr style="background-color: #3c8dbc; color:#fff">
                <th>Phòng</th>
                <th>Thứ tự</th>
                <th>Hiển thị</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data['rooms'] as $item) { ?>
                <tr>
                    <th scope="row" style="text-align:left">
                        <a href="/backend/roomtype/edit/<?php echo $item->id ?>"><?php echo $item->name ?></a>
                    </th>
                    <td>
                        <?php echo $item->position ?>
                    </td>
                    <td align="center" class="isshow" data-id="<?php echo $item->id ?>">
                        <?php if ($item->is_show == '1') : ?>
                            <a class="delete-btn add-button-disable" href="#" disabled="disabled"><i
                                    class="fa fa-check-circle" id="idshow-<?php echo $item->id ?>"></i></a>
                        <?php else: ?>
                            <a class="delete-btn add-button-disable" href="#" disabled="disabled"><i
                                    class="fa fa-times" id="idshow-<?php echo $item->id ?>"></i></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</section><!-- /.content -->
<?php echo $this->tag->endForm(); ?>
<script type="text/javascript">
    var is_loading = false;
    $(document).ready(function () {
        $('.isshow').off('click').on('click', function (e) {
            e.preventDefault();
            var link = $(this);
            var id = link.data('id');
            $.ajax({
                url: '/backend/roomtype/changeshow',
                type: 'POST',
                data: {id: id},
                dataType: 'text',
                success: function (result) {
                    var show = '#idshow-' + id;
                    $(show).attr("class", result);
                    is_loading = false;
                }
            });
        });
    });
</script>
