<?php echo $this->getContent() ?>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php
echo $this->tag->form(
    array(
        "index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "roomtypeform",
        "method" => "get"
    )
);
?>
<section class="content-header">
    <h2>
        Danh sách bài viết
    </h2>
    <div class="arrange-button">
        <a href="/backend/roomtype/new/" class="btn btn-info" id="modaltrigger" rel="leanModal">Thêm mới</a>
    </div>
</section>
<section class="content">
    <div class="sidebar-form">
        <div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Tên phòng"
                           value="<?php echo $data['filter'] ?>">
                        <span class="input-group-btn">
                            <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                            </button>
                        </span>
                </div>
            </div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Danh mục bài viết</span>
                    <select class="form-control" id="idlang" name="idlang">
                        <option value="" selected>Tất cả</option>
                        <?php foreach ($data["langs"] as $items): ?>
                            <?php if ($items->id == $data['idlang'])
                                echo "<option value=\"$items->id\" selected>$items->lang</option>";
                            else
                                echo "<option value=\"$items->id\">$items->lang</option>";
                            ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr style="background-color: #3c8dbc; color:#fff">
                <th>Phòng</th>
                <th>Vị trí</th>
                <th>Hiển thị</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data['rooms'] as $item) { ?>
                <tr>
                    <th scope="row" style="text-align:left">
                        <a href="edit/<?php echo $data['rooms']->items[$i]->id ?>"><?php echo $data['listnews']->items[$i]->title ?></a>
                    </th>
                    <td>
                        <?php
                        if ($data['listnews']->items[$i]->datecreate != '')
                            echo DateTime::createFromFormat('YmdHis', $data['listnews']->items[$i]->datecreate)->format('d/m/Y');
                        ?>
                    </td>
                    <td align="center">
                        <?php if ($data['listnews']->items[$i]->is_status == '1')
                            echo '<input class="check-box" disabled="disabled" type="checkbox" checked>';
                        else
                            echo '<input class="check-box" disabled="disabled" type="checkbox">';
                        ?>
                    </td>
                    <td>
                        <?php echo $data['listnews']->items[$i]->position ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <nav style="text-align:right">
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("/backend/news/index", "First") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/news/index?page=" . $data['listnews']->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/news/index?page=" . $data['listnews']->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/news/index?page=" . $data['listnews']->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</section><!-- /.content -->
<?php echo $this->tag->endForm(); ?>
<script type="text/javascript">
    $('#DateFrom').datetimepicker({
        value: '<?php echo $data['dateFrom'] ?>', step: 1
    });
    $('#DateTo').datetimepicker({
        value: '<?php echo $data['dateTo'] ?>', step: 1
    });
</script>
