<div class="header">
    <nav class="pre-menu invisible-premenu" style="display:none">
        <ul>
            <?php foreach ($datamain['menu'] as $item) : ?>
                <li>
                    <a href="/<?php echo $item->url . '/' . $item->slug_category ?>"><?php echo $item->name ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
    <div class="news-header">
        <div class="main-header-index"><!-- Main-header -->
            <div class="container">
                <div class="row1 clearfix">
                    <div class="pull-left">
                        <div class="logo">
                            <a href="/index"><img alt="Logo" src="/images/logo.svg" class="img-responsive"
                                                  width="70" height="33"/></a>
                        </div>
                    </div>
                    <div class="pull-right">
                        <nav class="nav clearfix invisible-menu">
                            <ul id="navigate" class="sf-menu navigate">
                                <?php foreach ($datamain['menu'] as $item) : ?>
                                    <li class="parent-menu">
                                        <a href="/<?php echo $item->url . '/' . $item->slug_category ?>"><?php echo $item->name ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </nav>
                        <div class="nav1">
                            <div id="nav-icon1" class="clearfix">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h1><?php echo $data['menutitle'] ?></h1>
        <?php if (isset($data['menusub'])): ?>
            <ul class="breadcrumb">
                <?php foreach ($data['menusub'] as $itemsub): ?>
                    <?php if (isset($itemsub->slug)): ?>
                        <li><a href="/news/<?php echo $itemsub->slug ?>"><?php echo $itemsub->name ?></a></li>
                    <?php else: ?>
                        <li><a href="/news/<?php echo $itemsub['slug'] ?>"><?php echo $itemsub['name'] ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>