<div class="header"><!-- Header Section -->
    <div class="main-header-index"><!-- Main-header -->
        <div class="container">
            <div class="row">
                <div class="pull-left">
                    <div class="logo">
                        <a href="index.html"><img alt="Logo" src="/images/logo.svg" class="img-responsive" width="70" height="33"/></a>
                    </div>
                </div>
                <div class="pull-right">
                    <div class="pull-left">
                        <nav class="nav clearfix">
                            <ul id="navigate" class="sf-menu navigate">
                                <li class="parent-menu active"><a href="index.html">HOMEPAGE</a>
                                </li>
                                <li class="parent-menu"><a href="#">FEATURES</a>
                                </li>
                                <li class="parent-menu"><a href="#">PAGES</a>
                                </li>
                                <li><a href="blog.html">NEWS</a></li>
                                <li><a href="contact.html">CONTACT</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>