<div class="quick-reservation clearfix">
    <div class="title-quick pos-center margint30">
        <h5>QUICK RESERVATIONS</h5>
        <div class="line"></div>
    </div>
    <div class="reserve-form-area">
        <form action="#" method="post" name="reserveform" id="ajax-reservation-form">
            <label>NGÀY NHẬN PHÒNG</label>
            <input type="text" id="dpd1" name="dpd1" class="date-selector" placeholder="&#xf073;" />
            <label>NGÀY TRẢ PHÒNG</label>
            <input type="text" id="dpd2" name="dpd2" class="date-selector" placeholder="&#xf073;" />
            <label>TÊN</label>
            <input type="text" id="dpd3" name="dpd3" class="date-selector" placeholder="&#xf073;" />
            <label>SỐ ĐIỆN THOẠI</label>
            <input type="text" id="dpd3" name="dpd3" class="date-selector" placeholder="&#xf073;" />
            <label>lOAI PHÒNG</label>
            <select name="rooms" class="date-selector">
                <option selected="selected" value="1" >1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <div class="pull-left children clearfix">
                <label>ROOMS</label>
                <select name="rooms" class="pretty-select">
                    <option selected="selected" value="1" >1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="pull-left type clearfix">
                <label>ADULT</label>
                <select name="adult" class="pretty-select">
                    <option selected="selected" value="1" >1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="pull-left rooms clearfix">
                <label>CHILDREN</label>
                <select name="children" class="pretty-select">
                    <option selected="selected" value="0" >0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="pull-left search-button clearfix">
                <div class="button-style-1">
                    <a id="res-submit" href="#">SEARCH</a>
                </div>
            </div>
        </form>
    </div>
</div>