<?php echo $this->getContent(); ?>
<section class="news">
    <div class="news-header">
        <h1>Giới Thiệu</h1>
        <span>Giới Thiệu Tập Đoàn Hoàn Cầu</span>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <article>
                <header>
                    <h3><?php echo $data->title; ?></h3>
                    <div class="meta">
                        <span><?php echo DateTime::createFromFormat('YmdHis', $data->datecreate)->format('d/m/Y');?></span>
                    </div>
                </header>
                <div>
                    <?php echo $data->content; ?>
                </div>
            </article>
        </div>
    </div>
</div>