<?php echo $this->getContent(); ?>
<div id="wrapper">

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <article>
                <header>
                    <h3><?php echo $data->title; ?></h3>
                    <div class="meta">
                        <span><?php echo DateTime::createFromFormat('YmdHis', $data->datecreate)->format('d/m/Y');?></span>
                    </div>
                </header>
                <div>
                    <?php echo $data->content; ?>
                </div>
            </article>
        </div>
    </div>
</div>
</div>