<?php echo $this->getContent(); ?>
<section class="news">
    <div class="news-header">
        <h1>Bản đồ</h1>
        <span>Bảng đồ Dinh I</span>
    </div>
    <div class="menu-common">
        <div class="decor"></div>
        <ul>
            <li><a href="#">Dinh I</a></li>
        </ul>
        <div class="decor"></div>
    </div>
    <div class="map-content">
        <div class="img-overlay">
            <img src="/images/so-do-Dinh.jpg" alt="">
        </div>
        <div class="box-content1">
            <div class="content1 box">
                <h4>Quầy Vé</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content2">
            <div class="content2 box">
                <h4>Bãi Đậu Xe Gắn Máy</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content3">
            <div class="content3 box">
                <h4>Bãi Đậu Xe O To</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content4">
            <div class="content4 box">
                <h4>Biệt Thự A</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content5">
            <div class="content5 box">
                <h4>Biệt Thự B</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content6">
            <div class="content6 box">
                <h4>Hàm Cây Tràm Trắng</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content7">
            <div class="content7 box">
                <h4>Đài Phun Nước</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content8">
            <div class="content8 box">
                <h4>Cây Chà Là</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content9">
            <div class="content9 box">
                <h4>Lo Cốt</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content10">
            <div class="content10 box">
                <h4>Bồn Hoa Chính</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content11">
            <div class="content11 box">
                <h4>Xe Thức Ăn, Xe Ngựa</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content12">
            <div class="content12 box">
                <h4>Dinh 1</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content13">
            <div class="content13 box">
                <h4>Đài Phun Nước Trung Tâm</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content14">
            <div class="content14 box">
                <h4>Cà Phê Thượng Uyển</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content15">
            <div class="content15 box">
                <h4>Quầy Lưu Niệm</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content16">
            <div class="content16 box">
                <h4>Khu Vực WC Công Cộng</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content17">
            <div class="content17 box">
                <h4>Khu Cà Phê</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content18">
            <div class="content18 box">
                <h4>Hệ Thống Đường Hầm</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content19">
            <div class="content19 box">
                <h4>Bải Đáp Trực Thăng</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
        <div class="box-content20">
            <div class="content20 box">
                <h4>Hồ Tắm Nam Phương</h4>
            </div>
            <div class="circle-plus">
                <div class="circle">
                    <div class="horizontal"></div>
                    <div class="vertical"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        $('.box-content1 .circle-plus').mouseenter(function () {
            $('.content1').removeClass('box').addClass('box1');
        });
        $('.box-content1 .circle-plus').mouseleave(function () {
            $('.content1').removeClass('box1').addClass('box');
        });
        $('.box-content2 .circle-plus').mouseenter(function () {
            $('.content2').removeClass('box').addClass('box1');
        });
        $('.box-content2 .circle-plus').mouseleave(function () {
            $('.content2').removeClass('box1').addClass('box');
        });
        $('.box-content3 .circle-plus').mouseenter(function () {
            $('.content3').removeClass('box').addClass('box1');
        });
        $('.box-content3 .circle-plus').mouseleave(function () {
            $('.content3').removeClass('box1').addClass('box');
        });
        $('.box-content4 .circle-plus').mouseenter(function () {
            $('.content4').removeClass('box').addClass('box1');
        });
        $('.box-content4 .circle-plus').mouseleave(function () {
            $('.content4').removeClass('box1').addClass('box');
        });
        $('.box-content5 .circle-plus').mouseenter(function () {
            $('.content5').removeClass('box').addClass('box1');
        });
        $('.box-content5 .circle-plus').mouseleave(function () {
            $('.content5').removeClass('box1').addClass('box');
        });
        $('.box-content6 .circle-plus').mouseenter(function () {
            $('.content6').removeClass('box').addClass('box1');
        });
        $('.box-content6 .circle-plus').mouseleave(function () {
            $('.content6').removeClass('box1').addClass('box');
        });
        $('.box-content7 .circle-plus').mouseenter(function () {
            $('.content7').removeClass('box').addClass('box1');
        });
        $('.box-content7 .circle-plus').mouseleave(function () {
            $('.content7').removeClass('box1').addClass('box');
        });
        $('.box-content8 .circle-plus').mouseenter(function () {
            $('.content8').removeClass('box').addClass('box1');
        });
        $('.box-content8 .circle-plus').mouseleave(function () {
            $('.content8').removeClass('box1').addClass('box');
        });
        $('.box-content9 .circle-plus').mouseenter(function () {
            $('.content9').removeClass('box').addClass('box1');
        });
        $('.box-content9 .circle-plus').mouseleave(function () {
            $('.content9').removeClass('box1').addClass('box');
        });
        $('.box-content10 .circle-plus').mouseenter(function () {
            $('.content10').removeClass('box').addClass('box1');
        });
        $('.box-content10 .circle-plus').mouseleave(function () {
            $('.content10').removeClass('box1').addClass('box');
        });
        $('.box-content11 .circle-plus').mouseenter(function () {
            $('.content11').removeClass('box').addClass('box1');
        });
        $('.box-content11 .circle-plus').mouseleave(function () {
            $('.content11').removeClass('box1').addClass('box');
        });
        $('.box-content12 .circle-plus').mouseenter(function () {
            $('.content12').removeClass('box').addClass('box1');
        });
        $('.box-content12 .circle-plus').mouseleave(function () {
            $('.content12').removeClass('box1').addClass('box');
        });
        $('.box-content13 .circle-plus').mouseenter(function () {
            $('.content13').removeClass('box').addClass('box1');
        });
        $('.box-content13 .circle-plus').mouseleave(function () {
            $('.content13').removeClass('box1').addClass('box');
        });
        $('.box-content14 .circle-plus').mouseenter(function () {
            $('.content14').removeClass('box').addClass('box1');
        });
        $('.box-content14 .circle-plus').mouseleave(function () {
            $('.content14').removeClass('box1').addClass('box');
        });
        $('.box-content15 .circle-plus').mouseenter(function () {
            $('.content15').removeClass('box').addClass('box1');
        });
        $('.box-content15 .circle-plus').mouseleave(function () {
            $('.content15').removeClass('box1').addClass('box');
        });
        $('.box-content16 .circle-plus').mouseenter(function () {
            $('.content16').removeClass('box').addClass('box1');
        });
        $('.box-content16 .circle-plus').mouseleave(function () {
            $('.content16').removeClass('box1').addClass('box');
        });
        $('.box-content17 .circle-plus').mouseenter(function () {
            $('.content17').removeClass('box').addClass('box1');
        });
        $('.box-content17 .circle-plus').mouseleave(function () {
            $('.content17').removeClass('box1').addClass('box');
        });
        $('.box-content18 .circle-plus').mouseenter(function () {
            $('.content18').removeClass('box').addClass('box1');
        });
        $('.box-content18 .circle-plus').mouseleave(function () {
            $('.content18').removeClass('box1').addClass('box');
        });
        $('.box-content19 .circle-plus').mouseenter(function () {
            $('.content19').removeClass('box').addClass('box1');
        });
        $('.box-content19 .circle-plus').mouseleave(function () {
            $('.content19').removeClass('box1').addClass('box');
        });
        $('.box-content20 .circle-plus').mouseenter(function () {
            $('.content20').removeClass('box').addClass('box1');
        });
        $('.box-content20 .circle-plus').mouseleave(function () {
            $('.content20').removeClass('box1').addClass('box');
        });
    });
</script>