<?php echo $this->getContent(); ?>
<section class="news">
    <div class="news-header">
        <h1>Muc Tin</h1>
        <span>tin tức cập nhập thường xuyên</span>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <article>
                <header>
                    <h3>TRẢI NGHIỆM CÁC CUNG ĐƯỜNG ĐÈO ĐẸP VÀO ĐÀ LẠT</h3>
                    <div class="meta">
                        <span><time datetime="1914-12-20 08:30:45.687">Dec 20, 2016</span>
                        <span>admin</span>
                    </div>
                </header>
                <div>
                    <img class="img-responsive" src="images/bg-5.png" alt="">
                    <p>
                        Tháng 9 là lúc những cơn mưa mùa hạ bắt đầu thưa dần, để lại những mảng màu đặc trưng của mùa thu trong không khí se lạnh. Cảm giác dễ chịu, khiến ai nấy đều khoan khoái và hào hứng ghé thăm Đà Lạt, dù không phải lần đầu đến.
                    </p>
                </div>
            </article>
        </div>
    </div>
</div>