<?php echo $this->getContent(); ?>
<div id="wrapper">
<div class="news">
    <div class="news-header">
        <div class="main-header"><!-- Main-header -->
            <div class="container">
                <div class="row1 clearfix">
                    <div class="pull-left">
                        <div class="logo">
                            <a href="index.html"><img alt="Logo" src="/images/logo.svg" class="img-responsive" width="70" height="33"/></a>
                        </div>
                    </div>
                    <div class="pull-right">
                        <nav class="nav clearfix">
                            <ul id="navigate" class="sf-menu navigate">
                                <li class="parent-menu active"><a href="index.html">HOMEPAGE</a>
                                </li>
                                <li class="parent-menu"><a href="#">FEATURES</a>
                                </li>
                                <li class="parent-menu"><a href="#">PAGES</a>
                                </li>
                                <li><a href="blog.html">NEWS</a></li>
                                <li><a href="contact.html">CONTACT</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <h1>Muc Tin</h1>
        <ul class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">news</a></li>
            <li><a href="#">tin-moi</a></li>
        </ul>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <article>
                <header>
                    <h3><?php echo $data->title ?></h3>
                    <div class="meta">
                        <span><time datetime=""><?php echo DateTime::createFromFormat('YmdHis', $data->datecreate)->format('d/m/Y') ?></time></span>
                    </div>
                </header>
                <div>
                    <?php echo $data->content ?>
                </div>
            </article>
        </div>
    </div>
</div>
</div>