<?php echo $this->getContent(); ?>
<input type="hidden" name="menutitle" value="<?php echo $data['menutitle'] ?>">
<div id="wrapper">
<div class="news">
    <div class="menu-common">
        <div class="decor"></div>
        <ul>
            <?php foreach ($data['cat'] as $items): ?>
                <li><a href="/news/<?php echo $items->slug ?>"><?php echo $items->name ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="decor"></div>
    </div>
    <div class="news-content">
        <div class="container">
            <div class="row">
                <div class="special col-md-6">
                    <?php if ($data['data']->count() == 0): ?>

                    <?php else: ?>
                        <?php foreach ($data['data'] as $items): ?>
                            <img class="img-responsive" src="<?php echo '\\' . $items->avatar_image ?>"
                                 alt="hinh">
                            <div class="special-content">
                                <h3><?php echo $items->title ?></h3>
                                <p><?php echo $items->content_short ?></p>
                                <div class="button">
                                    <a class="special-button" href="<?php echo '\\news\\detail\\' . $items->slug ?>">đọc
                                        thêm</a>
                                </div>
                            </div>
                            <?php break; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div class="right-news col-md-6">
                    <div class="row">
                        <?php if ($data['data']->count() > 0): ?>
                            <?php foreach ($data['data'] as $items): ?>
                                <div class="col-md-6">
                                    <img class="img-responsive" src="/<?php echo  $items->avatar_image ?>"
                                         alt="hinh to nhat">
                                    <div class="content">
                                        <span>23/12/1988</span>
                                        <h3><?php echo $items->title ?></h3>
                                        <p><?php echo $items->content_short ?></p>
                                        <a class="new-button" href="<?php echo '\\news\\detail\\' . $items->slug ?>">đọc
                                            thêm</a>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="row">
                        <?php if ($data['data']->count() > 0): ?>
                            <?php foreach ($data['data'] as $items): ?>
                                <div class="col-md-6">
                                    <img class="img-responsive" src="/<?php echo  $items->avatar_image ?>"
                                         alt="hinh to nhat">
                                    <div class="content">
                                        <span>23/12/1988</span>
                                        <h3><?php echo $items->title ?></h3>
                                        <p><?php echo $items->content_short ?></p>
                                        <a class="new-button" href="<?php echo '\\news\\detail\\' . $items->slug ?>">đọc
                                            thêm</a>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="latest-new">
                <p>Tin tức</p>
            </div>
            <div id="pagenews" class=“row”>

            </div>
        </div>
    </div>
</div>
</div>
<script defer type="text/javascript">
    var is_loading = false; // initialize is_loading by false to accept new loading
    var pages = 1;
    var end = 'false';
    var catid = <?php echo $data['catid'];?>;
    $(document).ready(function () {
        $(window).scroll(function () {
            var page = {'page': pages, 'endpage': end, 'catid': catid};
            if (is_loading == false & end == 'false') {
                is_loading = true;
                $.ajax({
                    url: '/frontend/news/loadmorenews',
                    type: 'POST',
                    data: page,
                    dataType: 'json',
                    success: function (result) {
                        if (result.endload != 'end') {
                            var html = '<div id="pagenews" class="row right-news" data-page="' + pages + '">';
                            $.each(result.listnews, function (key, item) {
                                html += '<div class="news-frame col-md-3">';
                                html += '<img class="img-responsive" src="/' + item.avatar_image + '" alt="hinh to nhat">';
                                html += '<div class="special-content">';
                                html += '<h3>' + item.title + '</h3>';
                                html += '<p>' + item.content_short + '</p>';
                                html += '<a class="new-button" href="/news/detail/' + item.slug + '">đọc thêm</a>';
                                html += '</div>';
                                html += '</div>';
                            });
                            html += '</div>';
                            $('#pagenews').append(html);
                        }
                        // append: add the new statments to the existing data
                        pages = result.nextpage;
                        end = result.endpage;
                        // set is_loading to false to accept new loading
                        is_loading = false;
                    },
                    error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
            }
        });
    });
</script>
