<?php echo $this->getContent(); ?>
<div id="wrapper">
<div class="contact">
    <div id="contact-wrapper" class="container">
        <div class="row">
            <div class="col-md-8">
                <h4>Get in touch</h4>
                <form action="/contact/create" method="post" id="contactform" class="contact-form row">
                    <div class="col-md-6 col-sm-12">
                        <label for="yourname" class="field">
                            <input type="text" id="namecontact" name="namecontact" placeholder="Họ Tên" maxlength="64">
                            <span class="icon-user icon"></span>
                        </label>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label for="youremail" class="field">
                            <input type="email" id="emailcontact" name="emailcontact" placeholder="Email">
                            <span class="icon-mail2 icon"></span>
                        </label>
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <label for="subject" class="field">
                            <input type="text" id="subjectcontact" name="subjectcontact" placeholder="Tiêu đề" maxlength="64">
                            <span class="icon-book icon"></span>
                        </label>
                    </div>
                    <div class="col-md-12 col-sm-12" field>
                        <label for="message" class="field clearHeight">
                            <textarea rows="5" id="messagecontact" name="messagecontact" placeholder="Nội dung"
                                      maxlength="1024"></textarea>
                            <span class="icon-bubbles2 icon"></span>
                        </label>
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <button name="submit" type="submit" id="contact-submit">Send Email</button>
                    </div>
                </form>
            </div>
            <div class="contact-info col-md-4 col-centered">
                <h4>Contact Info</h4>
                <address>
                    <p><i class="icon-home2"></i><strong>Văn phòng:</strong><span><?php echo $datamain['data']->address ?></span>
                    </p>
                    <p><i class="icon-phone"></i><strong>Tel :</strong><?php echo $datamain['data']->cellphone ?></p>
                    <p><i class="icon-printer"></i><strong>Fax :</strong><?php echo $datamain['data']->fax ?></p>
                    <p><i class="icon-envelop"></i><strong>Email :</strong><?php echo $datamain['data']->email ?></p>
                </address>
                <div class="social-networks">
                    <h4>Social Networking</h4>
                    <nav>
                        <ul>
                            <li><a href="<?php echo $datamain['data']->facebook; ?>"><i class="icon-facebook3"></i></a></li>
                            <li><a href="#"><i class="icon-twitter"></i></a></li>
                            <li><a href="#"><i class="icon-pinterest"></i></a></li>
                            <li><a href="#"><i class="icon-google-plus3"></i></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div><!-- Container contact info-->
    <div class="map-wrapper">
        <div class="map-canvas" id="map-canvas"></div>
    </div>
</div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDW2AX9aSZHqh0c1hxI19cWZLUyEkDeo6k"></script>

<script type="text/javascript">
    function initialize() {
        // set up coordinate
        var latlng = new google.maps.LatLng(11.9443829, 108.4676117,17);
        var latlngbachai = new google.maps.LatLng(10.780098, 106.65813);
        // call the map into ui
        var map = new google.maps.Map(
            document.getElementById('map-canvas'), {
                center: latlng,
                zoom: 18,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
        // cotent infowindow
        var addr= '<?php echo $datamain['data']->address ?>';
        var phone ='<?php echo $datamain['data']->cellphone ?>';
        var companyname ='<?php echo $datamain['data']->companyname ?>';
        var contentString = '<div>' +
            '<h4>'+ companyname +'</h4>' +
            '<div>' +
            '<p><strong>Address : </strong>'+ addr +'</p>' +
            '<p><strong>Phone : </strong>'+phone+'</p>' +
            '<img alt="cong ty" src="images">' +
            '</div>' +
            '</div>';

        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title: "hello world!"
        });
        //center map when resize
        google.maps.event.addDomListener(window, "resize", function () {
            var center = map.getCenter();
            google.maps.event.trigger(map, "resize");
            map.setCenter(center);
        });

        infowindow.open(map, marker);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    $().ready(function () {
        // validate signup form on keyup and submit
        $("#contactform").validate({
            rules: {
                namecontact: {
                    required: true,
                    minlength: 4
                },
                emailcontact: {
                    required: true,
                    email: true
                },
                subjectcontact: {
                    required: true,
                    minlength: 4
                },
                messagecontact: {
                    required: true,
                    minlength: 4
                }
            },
            messages: {
                namecontact: {
                    required: "Nhập tên",
                    minlength: "Lớn hơn 4 ký tự"
                },
                emailcontact: {
                    required: "Nhập email",
                    email: "Không đúng định dạng email"
                },
                subjectcontact: {
                    required: "Nhập tên",
                    minlength: "Nội dung quá ngắn"
                },
                messagecontact: {
                    required: "Nhập nội dung",
                    minlength: "Nội dung quá ngắn"
                }
            }
        });
    });
</script>