<?php echo $this->getContent() ?>
<?php
echo $this->tag->form(
    array(
        "backend/picture/create",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "id" => "createPic"
    )
);
?>
    <section class="content-header">
        <h2>Tạo mới album</h2>
        <div class="validation-summary-valid" data-valmsg-summary="true">
            <ul>
                <li style="display:none"></li>
            </ul>
        </div>
    </section>
    <section class="content">
        <div class="arrage-popup">
            <div class="arrange-div form-group col-md-12">
                <label class="text-label col-md-2" for="cat">Chọn album</label>
                <div class="col-md-6">
                    <select class="form-control" id="lang" name="lang">
                        <?php foreach ($data as $items): ?>
                            <?php echo "<option value=\"$items->id\">$items->name</option>" ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="arrange-div form-group col-md-12">
                <label class="text-label col-md-2" for="Name"></label>
                <div class="col-md-6">
                    <div id="fine-uploader">
                    </div>
                    <!-- Fine Uploader -->
                    <script src="../fine-uploader.min.js" type="text/javascript"></script>
                    <script type="text/template" id="qq-template">
                        <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
                            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                                     class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
                            </div>
                            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                                <span class="qq-upload-drop-area-text-selector"></span>
                            </div>
                            <div class="qq-upload-button-selector qq-upload-button">
                                <div>Upload a file</div>
                            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
                            <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite"
                                aria-relevant="additions removals">
                                <li>
                                    <div class="qq-progress-bar-container-selector">
                                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                                             class="qq-progress-bar-selector qq-progress-bar"></div>
                                    </div>
                                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                                    <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                                    <span class="qq-upload-file-selector qq-upload-file"></span>
                                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"
                                      aria-label="Edit filename"></span>
                                    <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                                    <span class="qq-upload-size-selector qq-upload-size"></span>
                                    <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">
                                        Cancel
                                    </button>
                                    <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry
                                    </button>
                                    <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                                        Delete
                                    </button>
                                    <span role="status"
                                          class="qq-upload-status-text-selector qq-upload-status-text"></span>
                                </li>
                            </ul>

                            <dialog class="qq-alert-dialog-selector">
                                <div class="qq-dialog-message-selector"></div>
                                <div class="qq-dialog-buttons">
                                    <button type="button" class="qq-cancel-button-selector">Close</button>
                                </div>
                            </dialog>

                            <dialog class="qq-confirm-dialog-selector">
                                <div class="qq-dialog-message-selector"></div>
                                <div class="qq-dialog-buttons">
                                    <button type="button" class="qq-cancel-button-selector">No</button>
                                    <button type="button" class="qq-ok-button-selector">Yes</button>
                                </div>
                            </dialog>

                            <dialog class="qq-prompt-dialog-selector">
                                <div class="qq-dialog-message-selector"></div>
                                <input type="text">
                                <div class="qq-dialog-buttons">
                                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                                    <button type="button" class="qq-ok-button-selector">Ok</button>
                                </div>
                            </dialog>
                        </div>
                    </script>
                    <script>
                        var uploader = new qq.FineUploader({
                            debug: true,
                            element: document.getElementById('fine-uploader'),
                            request: {
                                endpoint: 'img/'
                            },
                            deleteFile: {
                                enabled: true,
                                endpoint: 'img/'
                            },
                            retry: {
                                enableAuto: true
                            }
                        });
                    </script>
                </div>
            </div>
            <div style="text-align:center" class="col-md-12">
                <input type="submit" value="Lưu" class="btn btn-info"/>
                <a href="/webdinhdalat/backend/picture/index" class="btn btn-info">Về danh sách</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </section>
<?php echo $this->tag->endForm(); ?>