<?php echo $this->getContent() ?>
<?php
echo $this->tag->form(
    array(
        "/backend/roombook/index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "roombookform",
        "method" => "get"
    )
);
?>
<section class="content-header">

</section>
<section class="content">
    <div class="sidebar-form">
        <div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <span class="input-group-btn">
                            <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                            </button>
                        </span>
                    <input type="text" name="filter" id="filter" class="form-control"
                           placeholder="Tìm tên hoặc điện thoại"
                           value="<?php echo $data['filter'] ?>">
                </div>
            </div>

        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr style="background-color: #3c8dbc; color:#fff">
                <th>Tên</th>
                <th>Điện thoại</th>
                <th>Ngày nhận phòng</th>
                <th>Ngày trả phòng</th>
                <th>Người lớn</th>
                <th>Người trẻ em</th>
                <th>Tình trạng</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data['data']->items as $item) { ?>
                <tr>
                    <th scope="row" style="text-align:left">
                        <?php echo $item->name ?>
                    </th>
                    <td>
                        <?php echo $item->cellphone ?>
                    </td>
                    <td>
                        <?php echo $item->checkin ?>
                    </td>
                    <td>
                        <?php echo $item->checkout ?>
                    </td>
                    <td>
                        <?php echo $item->persons ?>
                    </td>
                    <td>
                        <?php echo $item->children ?>
                    </td>
                    <td align="center">
                        <?php if ($item->is_status == '1') : ?>
                            <a class="" href="#" disabled="disabled"><i
                                    class="fa fa-check-circle" id="idshow-<?php echo $item->id ?>"></i></a>
                        <?php else: ?>
                            <a class="status" href="#" disabled="disabled" data-id="<?php echo $item->id ?>"><i
                                    class="fa fa-times" id="idshow-<?php echo $item->id ?>"></i></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <nav style="text-align:right">
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("/backend/roombook/index", "First") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/roombook/index?page=" . $data['data']->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/roombook/index?page=" . $data['data']->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("/backend/roombook/index?page=" . $data['data']->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</section><!-- /.content -->
<?php echo $this->tag->endForm(); ?>
<script type="text/javascript">
    var is_loading = false;
    $(document).ready(function () {
        $('.status').off('click').on('click', function (e) {
            e.preventDefault();
            var link = $(this);
            var id = link.data('id');
            $.ajax({
                url: '/backend/roombook/changestatus',
                type: 'POST',
                data: {id: id},
                dataType: 'text',
                success: function (result) {
                    var show = '#idshow-' + id;
                    $(show).attr("class", result);
                    is_loading = false;
                }
            });
        });
    });
</script>
