<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><?php echo $data['data']->title; ?></title>
    <meta name="description" content="<?php echo $data['data']->meta; ?>">
    <?php $this->assets->outputCss() ?>
    <script src="/js/jquery-1.12.4.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.datetimepicker.full.min.js"></script>
</head>
<body>
<div id="wrapper">
<div id="header">
    <header class="main-header-index">
        <a href="#"><img id="logo" src="/images/logo.svg" alt="King Palace"></a>
        <div id="nav-icon" class="clearfix">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </header>
    <div class="book-form">
        <?php $this->partial("share/book_form"); ?>
    </div>
    <nav class="navigator" style="display:none">
        <ul>
            <?php foreach ($data['menu'] as $item) : ?>
                <li>
                    <a href="/<?php echo $item->url . '/' . $item->slug_category ?>"><?php echo $item->name ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
    <div class="content-header">
        <div class="top-img">
            <img src="/images/kingicon.png" alt="">
        </div>
        <div class="content">
            <h1>King<span>Palace</span></h1>
            <p>Điểm tham quan di tích nổi tiếng Đà Lạt</p>
            <span class="since">Since 1940</span>
        </div>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
        <div class="scroll">
            <a href="#"><span></span></a>
        </div>
    </div>
    <div id="dd" class="wrapper-dropdown-2" tabindex="1">English
                <ul class="dropdown">
                    <li><a href="#">Vietnamese</a></li>
                </ul>
            </div>
</div>
<div id="organization">
    <div class="header-title">
        <h2 class="red">hoàn cầu đà lạt</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12 h-line">
                <p><?php echo $data['data']->introduce ?></p>
            </div>
            <div class="col-md-6 col-xs-12 col-centered"><img class="img-responsive" src="/images/organization.png"
                                                              alt="Organization"></div>
        </div>
    </div>
</div>
<div id="palace">
    <div class="header-title">
        <h2 class="yellow">các dinh thự vua bảo đại</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container content-palace">
        <div class="row row-centered">
            <div class="col-md-3 col-centered wrapper-content">
                <img src="/images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title"><?php echo $data['news'][1]->title; ?></h3>
                    <p><?php echo $data['news'][1]->content_short ?></p>
                    <div>
                        <a class="king-button" href="/news/detail/<?php echo $data['news'][1]->slug ?>">đọc thêm</a>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-centered wrapper-content wrapper-content-special">
                <img class="king-special" src="/images/king.png" alt="">
                <div class="content-special">
                    <h3 class="header-content-title"><?php echo $data['news'][0]->title; ?></h3>
                    <p><?php echo $data['news'][0]->content_short ?></p>
                    <div>
                        <a class="king-button" href="/news/detail/<?php echo $data['news'][0]->slug ?>">đọc thêm</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-centered wrapper-content">
                <img src="/images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title"><?php echo $data['news'][2]->title; ?></h3>
                    <p><?php echo $data['news'][2]->content_short ?></p>
                    <div>
                        <a class="king-button" href="/news/detail/<?php echo $data['news'][2]->slug ?>">đọc thêm</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="service">
    <div class="header-title">
        <h2 class="red">các loại hình dịch vụ</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container arrange">
        <div class="row">
            <?php foreach ($data['services'] as $item): ?>
                <div class="col-md-4 col-sm-4 col-centered">
                    <figure class="effect-blur">
                        <div><img class="img-responsive" src="/<?php echo $item->avatar_image ?>" alt="1"/></div>
                        <figcaption>
                            <h4 class="service-title"><a
                                    href="/news/detail/<?php echo $item->slug ?>"><?php echo $item->title ?></a></h4>
                        </figcaption>
                    </figure>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<div id="email-receive">
    <div class="header-title">
        <h2 class="yellow">nhận bài viết mới</h2>
    </div>
    <form action="/newsletter/create" method="post" id="letterform">
        <div class="email-box">
            <label for="email">
                <input type="text" id="emailletter" name="emailletter" value="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
            </label>
            <button name="letter-submit" type="submit" id="letter-submit">Đăng Ký</button>
        </div>
    </form>
</div>
</div>
<?php $this->partial("share/footer"); ?>
<script>
    function DropDown(el) {
                this.dd = el;
                this.initEvents();
            }
            DropDown.prototype = {
                initEvents : function() {
                    var obj = this;

                    obj.dd.on('click', function(event){
                        $(this).toggleClass('active');
                        event.stopPropagation();
                    }); 
                }
            }

            $(function() {

                var dd = new DropDown( $('#dd') );

                $(document).click(function() {
                    // all dropdowns
                    $('.wrapper-dropdown-2').removeClass('active');
                });

            });

    $('#datebook').datetimepicker({
        value: '', step: 1
    });
    $().ready(function () {
        $('#letterform').validate({
            rules: {
                emailletter: {
                    required: true,
                    email: 4
                }
            },
            messages: {
                emailletter: {
                    required: "Nhập email",
                    email: "Không đúng dịnh dạng"
                }
            }
        });
        // validate signup form on keyup and submit
        $("#bookform").validate({
            rules: {
                namebook: {
                    required: true,
                    minlength: 4
                },
                emailbook: {
                    required: true,
                    email: true
                },
                contentbook: {
                    required: true,
                    minlength: 4
                },
                phonebook: {
                    required: true,
                    number: true
                },
                datebook: {
                    required: true
                }
            },
            messages: {
                namebook: {
                    required: "Nhập tên",
                    minlength: "Lớn hơn 4 ký tự"
                },
                emailbook: {
                    required: "Nhập email",
                    email: "Không đúng định dạng email"
                },
                contentbook: {
                    required: "Nhập nội dung",
                    minlength: "Nội dung quá ngắn"
                },
                phonebook: {
                    required: "Nhập điện thoại",
                    number: "Nhập số"
                },
                datebook: {
                    required: "Nhập ngày"
                }
            }
        });
    });
</script>
</body>
</html>