<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><?php echo $data->title; ?></title>
    <link rel="stylesheet" href="../../css/frontend/main.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="../../js/main.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<section id="header">
    <header class="main-header">
        <a href="#"><img id="logo" src="images/logo.svg" alt="King Palace"></a>
        <div id="nav-icon">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </header>
    <nav class="navigator" style="display:none">
        <ul>
            <li><a href="#">giới thiệu</a></li>
            <li><a href="#">dịch vụ</a></li>
            <li><a href="#">bảng giá</a></li>
            <li><a href="#">bản đồ dinh</a></li>
            <li><a href="gallery">thư viện ảnh</a></li>
            <li><a href="news">tin tức</a></li>
            <li><a href="contact">liên hệ</a></li>
        </ul>
    </nav>
    <div class="content-header">
        <div class="top-img">
            <img src="images/kingicon.png" alt="">
        </div>
        <div class="content">
            <h1>King<span>Palace</span></h1>
            <p>Điểm tham quan di tích nổi tiếng Đà Lạt</p>
            <span class="since">Since 1940</span>
        </div>
        <div class="bottom-img">
            <img src="images/line.png" alt="">
        </div>
        <div class="scroll">
            <a href="#"><span></span></a>
        </div>
    </div>
</section>
<section id="organization">
    <div class="header-title">
        <h2 class="red">hoàn cầu đà lạt</h2>
        <div class="bottom-img">
            <img src="images/line.png" alt="">
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12 h-line">
                <p>Là một tập đoàn kinh doanh đa ngành nghề được thành lập vào năm 1993. Với 28 công ty thành viên hiện
                    có, Hoàn Cầu đã đầu tư, xây dựng vào các lĩnh vực trọng yếu: Dịch vụ giải trí - du lịch; Khu đô thị
                    - công nghiệp; Nhà hàng - khách sạn; Resort; Sân Golf; Khu dân cư cao cấp; Cao ốc - văn phòng; Trung
                    tâm Thương mại; Tài chính - ngân hàng…vv. Ở bất kỳ lĩnh vực ngành nghề nào, Hoàn Cầu Group cũng chú
                    trọng đến việc tạo dựng uy tín và chất lượng dịch vụ, sản phẩm của mình.
                    Tháng 11/2014, Hoàn Cầu Group chính thức trở thành chủ sở hữu mới của khu Dinh I và đã bỏ ra số vốn
                    đáng kể để tu sửa, tôn tạo lại Dinh I thành nơi thăm quan, du lịch hẫp dẫn dành cho du khách khi tới
                    Đà Lạt.
                </p>
            </div>
            <div class="col-md-6 col-xs-12 col-centered"><img class="img-responsive" src="images/organization.png"
                                                              alt="Organization"></div>
        </div>
    </div>
</section>
<section id="palace">
    <div class="header-title">
        <h2 class="yellow">các dinh thự vua bảo đại</h2>
        <div class="bottom-img">
            <img src="images/line.png" alt="">
        </div>
    </div>
    <div class="container content-palace">
        <div class="row row-centered">
            <div class="col-md-4 col-centered wrapper-content">
                <img src="images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title">dinh II</h3>
                    <p>Dinh II được xây dựng từ năm 1933 đến năm 1937, bởi bàn tay tài hoa của các kiến trúc sư người
                        Pháp. Vào năm 1942, toàn quyền Decoux đã làm việc tại đây. Chính vì vậy, Dinh còn có tên gọi là
                        “Dinh thự mùa hè” hay “Dinh thự toàn quyền”.
                    </p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-centered wrapper-content wrapper-content-special">
                <img class="king-special" src="images/king.png" alt="">
                <div class="content-special">
                    <h3 class="header-content-title">dinh I</h3>
                    <p>Dinh I nằm cách trung tâm thành phố Đà lạt không xa về hướng Đông-Nam trên độ cao 1,550m, Dinh 1
                        được bao quanh bởi rừng thông.
                    </p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-centered wrapper-content">
                <img src="images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title">dinh III</h3>
                    <p>Dinh III toạ lạc ở độ cao gần 1,600 mét, công trình được xây dựng bởi sự kết hợp giữa các kiến
                        trúc người Pháp và Việt Nam.
                    </p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="service">
    <div class="header-title">
        <h2 class="red">các loại hình dịch vụ</h2>
        <div class="bottom-img">
            <img src="images/line.png" alt="">
        </div>
    </div>
    <div class="container arrange">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/1.png" alt="1"/></div>
                    <figcaption>
                        <h4 class="service-title">tham quan dinh</h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/2.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title">chup hinh cưới</h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/3.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title">cho thuê tiệt cưới</h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/4.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title">tổ chức sự kiện Event</h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/5.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title">hoá trang vua chúa</h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="images/service/thumb/5.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title">cưởi ngựa đồi thông</h4>
                    </figcaption>
                </figure>
            </div>
        </div>
    </div>
</section>
<section id="email-receive">
    <div class="header-title">
        <h2 class="yellow">nhận bài viết mới</h2>
    </div>
    <div class="email-box">
        <label for="email">
            <input type="text" id="email" value="Email cua ban">
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </label>
        <button>Đăng Ký</button>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="company-info col-md-4 col-xs-12">
                <h4>công ty cổ phần hoàn cầu đà lạt</h4>
                <address>
                    Địa chỉ: <?php echo $data->address ?><br>
                    Điện thoại: <?php echo $data->cellphone ?> Fax: <?php echo $data->fax ?><br>
                    Email: <?php echo $data->email ?>
                </address>
            </div>
            <div class="company-logo col-md-4 col-xs-12">
                <img src="images/hoancau_logo.png" alt="">
            </div>
            <div class="social col-md-4 col-xs-12">
                <h4>Social Network</h4>
                <ul>
                    <li><a href="<?php echo $data->facebook; ?>"><i class="fa fa-facebook-square"
                                                                     aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</body>
</html>