<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><?php echo $data['data']->title; ?></title>
    <meta name="description" content="<?php echo $data['data']->meta; ?>">
    <?php $this->assets->outputCss() ?>
    <script src="/js/jquery-1.12.4.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.datetimepicker.full.min.js"></script>
</head>
<body>
<section id="header">
    <header class="main-header">
        <a href="#"><img id="logo" src="/images/logo.svg" alt="King Palace"></a>
        <div id="nav-icon">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </header>
    <div class="book-form">
        <img class="book" width="250" src="/images/king.png" alt="">
        <div id="book-wrapper" class="container">
            <div class="row">
                <div class="col-md-10 col-sm-12 col-centered">
                    <h3>Đặt Vé</h3>
                    <form action="/booking/create" method="post" id="bookform" class="contact-form row row-1">
                        <div class="col-md-6 col-sm-12">
                            <label for="yourname" class="field">
                                <input type="text" id="namebook" name="namebook" placeholder="Họ Tên" maxlength="64">
                                <span class="icon-user icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="youremail" class="field">
                                <input type="text" id="phonebook" name="phonebook" placeholder="Số Điện Thoại">
                                <span class="icon-phone icon"></span>
                            </label>
                        </div>
                        <div class="col-md-12 col-sm-12">
                            <label for="subject" class="field">
                                <input type="text" id="contentbook" name="contentbook" placeholder="Nội dung"
                                       maxlength="64">
                                <span class="icon-book icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="email" class="field">
                                <input type="text" id="emailbook" name="emailbook" placeholder="Email">
                                <span class="icon-mail2 icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="youremail" class="field">
                                <input type="text" id="datebook" name="datebook">
                                <span class="icon-calendar icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <img class="img-responsive" src="/images/captcha.jpg" alt="">
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <button name="submit" type="submit" id="contact-submit">Send Email</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <nav class="navigator" style="display:none">
        <ul>
            <?php foreach ($data['menu'] as $item) : ?>
                <li>
                    <a href="/<?php echo $item->url . '/' . $item->slug_category ?>"><?php echo $item->name ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
    <div class="content-header">
        <div class="top-img">
            <img src="/images/kingicon.png" alt="">
        </div>
        <div class="content">
            <h1>King<span>Palace</span></h1>
            <p>Điểm tham quan di tích nổi tiếng Đà Lạt</p>
            <span class="since">Since 1940</span>
        </div>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
        <div class="scroll">
            <a href="#"><span></span></a>
        </div>
    </div>
</section>
<section id="organization">
    <div class="header-title">
        <h2 class="red">hoàn cầu đà lạt</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12 h-line">
                <p><?php echo $data['data']->introduce ?></p>
            </div>
            <div class="col-md-6 col-xs-12 col-centered"><img class="img-responsive" src="/images/organization.png"
                                                              alt="Organization"></div>
        </div>
    </div>
</section>
<section id="palace">
    <div class="header-title">
        <h2 class="yellow">các dinh thự vua bảo đại</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container content-palace">
        <div class="row row-centered">
            <div class="col-md-3 col-centered wrapper-content">
                <img src="/images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title"><?php echo $data['news'][1]->title; ?></h3>
                    <p><?php echo $data['news'][1]->content_short ?></p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-centered wrapper-content wrapper-content-special">
                <img class="king-special" src="/images/king.png" alt="">
                <div class="content-special">
                    <h3 class="header-content-title"><?php echo $data['news'][0]->title; ?></h3>
                    <p><?php echo $data['news'][0]->content_short ?></p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-centered wrapper-content">
                <img src="/images/king.png" alt="">
                <div class="content">
                    <h3 class="header-content-title"><?php echo $data['news'][2]->title; ?></h3>
                    <p><?php echo $data['news'][2]->content_short ?></p>
                    <div>
                        <button class="king-button">đọc thêm</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="service">
    <div class="header-title">
        <h2 class="red">các loại hình dịch vụ</h2>
        <div class="bottom-img">
            <img src="/images/line.png" alt="">
        </div>
    </div>
    <div class="container arrange">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/1.png" alt="1"/></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">tham quan dinh</a></h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/2.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">chup hinh cưới</a></h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/3.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">cho thuê tiệt cưới</a></h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/4.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">tổ chức sự kiện Event</a></h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/5.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">hoá trang vua chúa</a></h4>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4 col-sm-4 col-centered">
                <figure class="effect-blur">
                    <div><img class="img-responsive" src="/images/service/thumb/5.png" alt=""></div>
                    <figcaption>
                        <h4 class="service-title"><a href="#">cưởi ngựa đồi thông</a></h4>
                    </figcaption>
                </figure>
            </div>
        </div>
    </div>
</section>
<section id="email-receive">
    <div class="header-title">
        <h2 class="yellow">nhận bài viết mới</h2>
    </div>
    <form action="/newsletter/create" method="post" id="letterform">
        <div class="email-box">
            <label for="email">
                <input type="text" id="emailletter" name="emailletter" value="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
            </label>
            <button name="letter-submit" type="submit" id="letter-submit" >Đăng Ký</button>
        </div>
    </form>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="company-info col-md-4 col-xs-12">
                <h4>công ty cổ phần hoàn cầu đà lạt</h4>
                <address>
                    Địa chỉ: <?php echo $data['data']->address ?><br>
                    Điện thoại: <?php echo $data['data']->cellphone ?> Fax: <?php echo $data['data']->fax ?><br>
                    Email: <?php echo $data['data']->email ?>
                </address>
            </div>
            <div class="company-logo col-md-4 col-xs-12">
                <img src="/images/hoancau_logo.png" alt="">
            </div>
            <div class="social col-md-4 col-xs-12">
                <h4>Social Network</h4>
                <ul>
                    <li><a href="<?php echo $data['data']->facebook; ?>"><i class="fa fa-facebook-square"
                                                                            aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<script>
    $('#datebook').datetimepicker({
        value: '', step: 1
    });
    $().ready(function () {
        $('#letterform').validate({
            rules: {
                emailletter: {
                    required: true,
                    email: 4
                }
            },
            messages: {
                emailletter: {
                    required: "Nhập email",
                    email: "Không đúng dịnh dạng"
                }
            }
        });
        // validate signup form on keyup and submit
        $("#bookform").validate({
            rules: {
                namebook: {
                    required: true,
                    minlength: 4
                },
                emailbook: {
                    required: true,
                    email: true
                },
                contentbook: {
                    required: true,
                    minlength: 4
                },
                phonebook: {
                    required: true,
                    number: true
                },
                datebook: {
                    required: true
                }
            },
            messages: {
                namebook: {
                    required: "Nhập tên",
                    minlength: "Lớn hơn 4 ký tự"
                },
                emailbook: {
                    required: "Nhập email",
                    email: "Không đúng định dạng email"
                },
                contentbook: {
                    required: "Nhập nội dung",
                    minlength: "Nội dung quá ngắn"
                },
                phonebook: {
                    required: "Nhập điện thoại",
                    number: "Nhập số"
                },
                datebook: {
                    required: "Nhập ngày"
                }
            }
        });
    });
</script>
</body>
</html>