<?php echo $this->getContent() ?>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php
echo $this->tag->form(
    array(
        "backend/users/index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "userform",
        "method" => "get"
    )
);
?>
<section class="content-header">
    <h2>
        Danh sách user
    </h2>
    <div class="arrange-button">
        <a href="new" class="btn btn-info" id="modaltrigger" rel="leanModal">Thêm mới</a>
    </div>
</section>
<section class="content">
    <div class="sidebar-form">
        <div class="row">
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Tìm users...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                </div>
            </div>
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Danh Mục</span>
                    <select class="form-control" name="catid" id="catid" onchange="productViewForm.submit()">
                        <option value="0">Chọn danh mục</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr style="background-color: #3c8dbc; color:#fff">
                <th>Tên tài khoản</th>
                <th>Tình trạng</th>
                <th>Ngày tạoc</th>
                <th>#</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" style="text-align:left">
                Test
                </th>
                <td>001670</td>
                <td align="center">
                    1
                </td>
                <td>Test</td>
            </tr>
            </tbody>
        </table>
        <nav style="text-align:right">
            <ul class="pagination">

            </ul>
        </nav>
    </div>
</section><!-- /.content -->
<?php echo $this->tag->endForm(); ?>
