<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php echo $this->getContent() ?>
<?php
echo $this->tag->form(
    array(
        "backend/users/search",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "userform"
    )
);
?>
<section class="content-header">
    <h2>
        Danh sách user
    </h2>
    <div class="arrange-button">
        <a href="backend/users/new" class="btn btn-info" id="modaltrigger" rel="leanModal">Thêm mới</a>
    </div>
</section>
<section class="content">
    <div class="sidebar-form">
        <div class="row">
            <div class="form-group col-sm-3">
                <div class="input-group">
                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Tìm sản phẩm..." value="cau cut">
                        <span class="input-group-btn">
                            <button type="submit" onclick="userformSubmit()" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                </div>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr style="background-color: #3c8dbc; color:#fff">
                <th>Tên Sản Phẩm</th>
                <th>Mã Sản Phẩm</th>
                <th>Mã Danh Mục</th>
                <th>ĐVT</th>
                <th>Giá</th>
                <th>Đã Xoá</th>
                <th>Thêm</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" style="text-align:left">

                </th>
                <td>001670</td>
                <td align="center">
                    1
                </td>
                <td>Test</td>
                <td style="text-align:right">200,000</td>
                <td>
                    <input class="check-box" disabled="disabled" type="checkbox" />
                </td>
                <td>

                </td>
            </tr>
            </tbody>
        </table>
        <nav style="text-align:right">
            <div class="pagination-container"><ul class="pagination"><li class="active"><a>1</a></li></ul></div>
        </nav>
    </div>
</section><!-- /.content -->
<?php echo $this->tag->endForm(); ?>
