<?php echo $this->getContent(); ?>
<section class="gallery">
    <div class="gallery-header">
        <h1>Thư viện Ảnh</h1>
        <span>tin tức cập nhập thường xuyên</span>
    </div>
    <div class="menu-common">
        <div class="decor"></div>
        <ul>
            <?php foreach ($data['albums'] as $item): ?>
            <?php echo "<li><a href=\"#\">$item->name</a></li>" ?>
            <?php endforeach; ?>
        </ul>
        <div class="decor"></div>
    </div>
    <div class="gallery-content">
        <?php foreach ($data as $items): ?>
            <div class="text-content">
                <div class="overlay">
                    <img class="img-responsive" src="images/gallery/1.png" alt="nha">
                </div>
                <h3><a href="">vườn hoa</a></h3>
            </div>
        <?php endforeach; ?>
        <div class="text-content">
            <div class="overlay">
                <img class="img-responsive" src="images/gallery/1.png" alt="nha">
            </div>
            <h3><a href="">vườn hoa</a></h3>
        </div>
        <div class="text-content">
            <div class="overlay">
                <img class="img-responsive" src="images/gallery/2.png" alt="nha">
            </div>
            <h3><a href="">cưởi ngựa</a></h3>
        </div>
        <div class="text-content">
            <div class="overlay">
                <img class="img-responsive" src="images/gallery/1.png" alt="nha">
            </div>
            <h3><a href="">rừng thông</a></h3>
        </div>
        <div class="text-content">
            <div class="overlay">
                <img class="img-responsive" src="images/gallery/2.png" alt="nha">
            </div>
            <h3><a href="">nội thất trong dinh</a></h3>
        </div>
    </div>
</section>