<?php echo $this->getContent(); ?>
<div id="wrapper">
<div class="gallery">
    <div class="menu-common">
        <div class="decor"></div>
        <ul>
            <?php foreach ($data['data']->items as $item): ?>
                <?php echo "<li><a href=\"#\">$item->name</a></li>" ?>
            <?php endforeach; ?>
        </ul>
        <div class="decor"></div>
    </div>
    <div class="gallery-content" id="gallery-content">
        <div class="gallery-content container">
            <div class="row" id="row-content">
                <?php foreach ($data['data']->items as $item): ?>
                    <div class="text-content col-md-3">
                        <div class="overlay background-ov">
                            <img class="img-responsive" src="<?php echo '\\' . $item->dir ?>" alt="nha">
                        </div>
                        <h3><a id="myBtn" class="showimage" data-id="<?php echo $item->id ?>"><?php echo $item->name ?></a></h3>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
</div>
<script defer type="text/javascript">
    var is_loading = false; // initialize is_loading by false to accept new loading
    var pages = 2;
    var end = 'false';
    $(document).ready(function () {
        $(window).scroll(function () {
            var page = {'page': pages, 'endpage': end};
            if (is_loading == false & end == 'false') {
                is_loading = true;
                $.ajax({
                    url: '/gallery/morealbum',
                    type: 'POST',
                    data: page,
                    dataType: 'json',
                    success: function (result) {
                        if (result.endload != 'end') {
                            var html = '';
                            $.each(result.albums, function (key, item) {
                                html += '<div class="text-content col-md-3">'
                                html += '<div class="overlay background-ov">'
                                html += '<img class="img-responsive" src="\\' + item.dir + '" >'
                                html += '</div>'
                                html += '<h3><a href="/gallery/detail/' + item.id + '">' + item.name + '</a></h3>'
                                html += '</div>'
                                html += '</div>'
                            });

                            $('#row-content').append(html);
                        }
                        // append: add the new statments to the existing data
                        pages = result.nextpage;
                        end = result.endpage;
                        // set is_loading to false to accept new loading
                        is_loading = false;
                    },
                    error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
            }
        });
        $('.showimage').off('click').on('click', function (e) {
            e.preventDefault();
            var link = $(this);
            var id = link.data('id');
            if (is_loading == false) {
                is_loading = true;
                $.ajax({
                    url: '/gallery/detailalbum',
                    type: 'POST',
                    data: {id: id},
                    dataType: 'json',
                    success: function (result) {
                        is_loading = false;
                        $.fancybox.open(result);
                    }
                });

            }
        });

    });
</script>