<?php echo $this->getContent(); ?>
<section class="gallery">
    <div class="gallery-header">
        <h1>Thư viện Ảnh</h1>
        <span>tin tức cập nhập thường xuyên</span>
    </div>
    <div class="menu-common">
        <div class="decor"></div>
        <ul>
            <?php foreach ($data->items as $item): ?>
                <?php echo "<li><a href=\"#\">$item->name</a></li>" ?>
            <?php endforeach; ?>
        </ul>
        <div class="decor"></div>
    </div>
    <div class="gallery-content" id="gallery-content">
        <?php foreach ($data->items as $item): ?>
            <div class="gallery-content container">
                <div class="row" id="row-content">
                    <div class="text-content col-md-3">
                        <div class="overlay background-ov">
                            <img class="img-responsive" src="<?php echo '\\' . $item->dir ?>" alt="nha">
                        </div>
                        <h3><a href=""><?php echo $item->name ?></a></h3>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div id="gallery" style="display:none;">
    
        <img alt="Preview Image 1"
             src="images/thumbs/thumb1.jpg"
             data-image="images/big/image1.jpg"
             data-description="Preview Image 1 Description">
        
        <img alt="Preview Image 2"
             src="images/thumbs/thumb2.jpg"
             data-image="images/big/image2.jpg"
             data-description="Preview Image 2 Description">

        <img alt="Youtube Video"
             data-type="youtube"
             data-videoid="A3PDXmYoF5U"
             data-description="You can include youtube videos easily!">
             
        <img alt="Preview Image 3"
             src="images/thumbs/thumb3.jpg"
             data-image="images/big/image3.jpg"
             data-description="Preview Image 3 Description">

        <img alt="Vimeo Video"
             data-type="vimeo"
             src="http://i.vimeocdn.com/video/447294219_200x150.jpg"
             data-image="http://i.vimeocdn.com/video/447294219_640.jpg"
             data-videoid="73234449"
             data-description="This gallery can also play vimeo videos!">
                      
    </div>
</section>
<script defer type="text/javascript">
    var is_loading = false; // initialize is_loading by false to accept new loading
    var pages = 2;
    var end = 'false';
    $(document).ready(function () {
        $(window).scroll(function () {
            var page = {'page': pages, 'endpage': end};
            if (is_loading == false & end == 'false') {
                is_loading = true;
                $.ajax({
                    url: '/gallery/morealbum',
                    type: 'POST',
                    data: page,
                    dataType: 'json',
                    success: function (result) {
                        if (result.endload != 'end') {
                            var html = '';
                            $.each(result.albums, function (key, item) {
                                html += '<div class="text-content col-md-3">'
                                html += '<div class="overlay background-ov">'
                                html += '<img class="img-responsive" src="\\' + item.dir + '" >'
                                html += '</div>'
                                html += '<h3><a href="/gallery/detail/' + item.id + '">' + item.name + '</a></h3>'
                                html += '</div>'
                                html += '</div>'
                            });

                            $('#row-content').append(html);
                        }
                        // append: add the new statments to the existing data
                        pages = result.nextpage;
                        end = result.endpage;
                        // set is_loading to false to accept new loading
                        is_loading = false;
                    },
                    error: function (jqXHR, exception) {
                        var msg = '';
                        if (jqXHR.status === 0) {
                            msg = 'Not connect.\n Verify Network.';
                        } else if (jqXHR.status == 404) {
                            msg = 'Requested page not found. [404]';
                        } else if (jqXHR.status == 500) {
                            msg = 'Internal Server Error [500].';
                        } else if (exception === 'parsererror') {
                            msg = 'Requested JSON parse failed.';
                        } else if (exception === 'timeout') {
                            msg = 'Time out error.';
                        } else if (exception === 'abort') {
                            msg = 'Ajax request aborted.';
                        } else {
                            msg = 'Uncaught Error.\n' + jqXHR.responseText;
                        }
                        console.log(msg);
                    }
                });
            }
        });
        //Gallery Images
        jQuery("#gallery").unitegallery();
    });
</script>