<?php
use  Webdinhdalat\Commons\ParamsSEO as params;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php echo $this->tag->getTitle(); ?>
    <meta name="description" content="<?php echo params::$meta_description ?>">
    <?php $this->assets->outputCss() ?>
    <script src="/js/jquery-1.12.4.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.datetimepicker.full.min.js"></script>
</head>
<body>
<div class="book-form">
    <img class="book" width="250" src="/images/king.png" alt="">
    <div id="book-wrapper" class="container">
        <div class="row">
            <div class="col-md-10 col-sm-12 col-centered">
                <h3>Đặt Vé</h3>
                <form action="/" method="post" class="contact-form row row-1">
                        <div class="col-md-6 col-sm-12">
                            <label for="yourname" class="field">
                                <input type="text" id="yourname" name="yourname" placeholder="Họ Tên" required>
                                <span class="icon-user icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="youremail" class="field">
                                <input type="email" id="youremail" name="youremail" placeholder="Số Điện Thoại" required>
                                <span class="icon-phone icon"></span>
                            </label>
                        </div>
                        <div class="col-md-12 col-sm-12">
                            <label for="subject" class="field">
                                <input type="text" id="subject" name="subject" placeholder="Địa Chỉ">
                                <span class="icon-book icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="email" class="field">
                                <input type="text" id="email" name="email" placeholder="Email">
                                <span class="icon-mail2 icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <label for="youremail" class="field">
                                <input type="text" id="yourdate" name="yourdate">
                                <span class="icon-calendar icon"></span>
                            </label>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <img class="img-responsive" src="/images/captcha.jpg" alt="">
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <button name="submit" type="submit" id="contact-submit">Send Email</button>
                        </div>
                        <script>
                            $('#yourdate').datetimepicker({
                                value: '', step: 1
                            });
                        </script>
                    </form>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getContent(); ?>
<footer>
    <div class="container">
        <div class="row">
            <div class="company-info col-md-4 col-xs-12">
                <h4>công ty cổ phần hoàn cầu đà lạt</h4>
                <address>
                    Địa chỉ: Dinh I, Trần Quang Diệu, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng<br>
                    Điện thoại: 0633 58 59 58 Fax: 0633 59 59 56<br>
                    Email: dinh1dalat@gmail.com
                </address>
            </div>
            <div class="company-logo col-md-4 col-xs-12">
                <img src="/images/hoancau_logo.png" alt="">
            </div>
            <div class="social col-md-4 col-xs-12">
                <h4>Social Network</h4>
                <ul>
                    <li><a href=""><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</body>
</html>