<?php
use  Webdinhdalat\Commons\ParamsSEO as params;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php echo $this->tag->getTitle(); ?>
    <meta name="description" content="<?php echo params::$meta_description ?>">
    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>
</head>
<body>
<?php $this->partial("share/header"); ?>
<div class="book-form">
    <?php $this->partial("share/book_form"); ?>
</div>
<?php echo $this->getContent(); ?>
<?php $this->partial("share/footer"); ?>
<script>
    $('#datebook').datetimepicker({
        value: '', step: 1
    });
    $().ready(function () {
        // validate signup form on keyup and submit
        $("#bookform").validate({
            rules: {
                namebook: {
                    required: true,
                    minlength: 4
                },
                emailbook: {
                    required: true,
                    email: true
                },
                contentbook: {
                    required: true,
                    minlength: 4
                },
                phonebook: {
                    required: true,
                    number: true
                },
                datebook: {
                    required: true
                }
            },
            messages: {
                namebook: {
                    required: "Nhập tên",
                    minlength: "Lớn hơn 4 ký tự"
                },
                emailbook: {
                    required: "Nhập email",
                    email: "Không đúng định dạng email"
                },
                contentbook: {
                    required: "Nhập nội dung",
                    minlength: "Nội dung quá ngắn"
                },
                phonebook: {
                    required: "Nhập điện thoại",
                    number: "Nhập số"
                },
                datebook: {
                    required: "Nhập ngày"
                }
            }
        });
    });
</script>
</body>
</html>