<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php echo $this->tag->getTitle(); ?>
    <?php $this->assets->outputCss() ?>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<?php echo $this->getContent(); ?>
<footer>
    <div class="container">
        <div class="row">
            <div class="company-info col-md-4 col-xs-12">
                <h4>công ty cổ phần hoàn cầu đà lạt</h4>
                <address>
                    Địa chỉ: Dinh I, Trần Quang Diệu, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng<br>
                    Điện thoại: 0633 58 59 58			Fax: 0633 59 59 56<br>
                    Email: dinh1dalat@gmail.com
                </address>
            </div>
            <div class="company-logo col-md-4 col-xs-12">
                <img src="/images/hoancau_logo.png" alt="">
            </div>
            <div class="social col-md-4 col-xs-12">
                <h4>Social Network</h4>
                <ul>
                    <li><a href=""><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script defer type=”text/javascript” src="/js/main.js"></script>
</body>
</html>