<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="/webdinhdalat/public/css/backend/bootstrap.min.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/font-awesome.min.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/modalStyles.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/AdminLTE.min.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/skin-blue.min.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/jquery.datetimepicker.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/alertify.css" rel="stylesheet"/>
    <link href="/webdinhdalat/public/css/backend/semantic.min.css" rel="stylesheet"/>
    <title>Quản lý thông tin website</title>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a href="/Product/Index" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CTY TNHH</b> Hoàn Cầu</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>CTY TNHH</b> Hoàn Cầu</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <form action="backend/login/logoff" method="post" id="logoutForm">
                    <input name="__RequestVerificationToken" type="hidden"
                           value=""/>
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">

                        </li><!-- /.messages-menu -->
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="backend/users/index" class="dropdown-toggle" title="Tài khoản">
                                <!-- The user image in the navbar-->
                                <img src="/webdinhdalat/public/img/backend/avatar5.png" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">admin</span>
                            </a>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="javascript:document.getElementById('logoutForm').submit()"
                               data-toggle="control-sidebar"><i class="fa fa-power-off"></i></a>
                        </li>
                    </ul>
                </form>

            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="/webdinhdalat/public/img/backend/avatar5.png" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>admin</p>
                    <!-- Status -->
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">Danh Mục</li>
                <!-- Optionally, you can add icons to the links -->
                <li class="active"><a href="/webdinhdalat/backend/users/index"><i class="fa fa-product-hunt"></i> <span>Danh sách tài khoản</span></a>
                </li>
                <li class="active"><a href="/ProductPriceLocationSub/index"><i class="fa fa-database"></i> <span>Giá sản phẩm theo khu vực</span></a>
                </li>
                <li><a href="/Payment/Index"><i class="fa fa-credit-card"></i> <span>Công nợ</span></a></li>
                <li><a href="/Order/Index"><i class="fa fa-list-ol"></i> <span>Đơn hàng</span></a></li>
                <li><a href="/Account/Index"><i class="fa fa-user"></i> <span>Tài khoản</span></a></li>
            </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">
        <?php echo $this->getContent(); ?>
    </div>
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">

        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2016 <a href="#">CTY TNHH Hoàn Cầu.</a></strong>
    </footer>
</div>
</body>
</html>
