<div id="wrapper">
	<div class="hotel-content"><!-- Content Section -->
		<div class="container">
			<div class="row">
				<div class="col-lg-12"><!-- Room Gallery Slider -->
					<div class="room-gallery">

						<div class="flexslider-thumb falsenav">
							<ul class="slides">
								<?php foreach($data['album'] as $album ):?>
									<li data-thumb="/<?php echo $album->dir?>"><img alt="Slider 1" class="img-responsive" src="/<?php echo $album->dir?>"/></li>
								<?php endforeach;?>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-9 clearfix"><!-- Room Information -->
					<div class="col-lg-12 clearfix col-sm-12">
						<h4>GIỚI THIỆU PHÒNG</h4>
						<?php echo $data['hotel']->desc?>
					</div>

				</div>
				<div class="col-lg-3 clearfix"><!-- Sidebar -->
					<div class="quick-reservation-container">
						<?php $this->partial("share/quick_reservations"); ?>
					</div>
					<div class="luxen-widget news-widget">
						<div class="title">
							<h5>LIÊN HỆ</h5>
						</div>
						<ul class="footer-links">
							<li><p><i class="fa fa-map-marker"></i> Địa chỉ: <?php echo $datamain['data']->address ?></p></li>
							<li><p><i class="fa fa-phone"></i> Điện thoại: <?php echo $datamain['data']->cellphone ?> Fax: <?php echo $datamain['data']->fax ?></p></li>
							<li><p><i class="fa fa-envelope"></i> Email: <?php echo $datamain['data']->email ?></p></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>