<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Room Single | Luxen Premium Hotel Template</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<link rel="shortcut icon" href="img/favicon.ico" />
<!-- CSS FILES -->
<link rel="stylesheet" type="text/css" href="/css/frontend/Vendor/awesome-font/font-awesome.css">
<link rel="stylesheet" href="/css/frontend/reset.css">
<link rel="stylesheet" href="/css/frontend/hotel/bootstrap.min.css">

<link rel="stylesheet" href="/css/frontend/flexslider.css">
<link rel="stylesheet" href="/css/frontend/hotel/datepicker.css">
<link rel="stylesheet" href="/css/frontend/hotel/selectordie.css">
<link rel="stylesheet" href="/css/frontend/main.css">
<link rel="stylesheet" href="/css/frontend/responsive.css">
<script src="/js/jquery-1.12.4.min.js"></script>
<!-- Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
<![endif]-->
</head>
<body>
<!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
<div id="wrapper">
	<div class="room-detail">
		<div class="main-header-index"><!-- Main-header -->
			<div class="container">
				<div class="row">
					<div class="pull-left">
						<div class="logo">
							<a href="index.html"><img alt="Logo" src="/images/logo.svg" class="img-responsive" width="70" height="33"/></a>
						</div>
					</div>
					<div class="pull-right">
						<nav class="nav clearfix">
							<ul id="navigate" class="sf-menu navigate">
								<li class="parent-menu active"><a href="index.html">HOMEPAGE</a>
								</li>
								<li class="parent-menu"><a href="#">FEATURES</a>
								</li>
								<li class="parent-menu"><a href="#">PAGES</a>
								</li>
								<li><a href="blog.html">NEWS</a></li>
								<li><a href="contact.html">CONTACT</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<h1>ROOM DETAILS</h1>
		<ul class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">news</a></li>
            <li><a href="#">tin-moi</a></li>
        </ul>
	</div>
	<div class="hotel-content"><!-- Content Section -->
		<div class="container">
			<div class="row">
				<div class="col-lg-12"><!-- Room Gallery Slider -->
					<div class="room-gallery">
						<div class="margint40 marginb20"><h4>PHOTO GALLERY</h4></div>
						<div class="flexslider-thumb falsenav">
							<ul class="slides">
								<li data-thumb="/images/room-gallery-image-1.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-1.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-2.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-2.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-3.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-3.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-4.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-4.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-5.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-5.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-6.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-6.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-7.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-7.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-8.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-8.jpg"/></li>
								<li data-thumb="/images/room-gallery-image-9.jpg"><img alt="Slider 1" class="img-responsive" src="/images/room-gallery-image-9.jpg"/></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-9 clearfix"><!-- Room Information -->
					<div class="col-lg-8 clearfix col-sm-8">
						<h4>ROOM DESCRIPTION</h4>
						<p class="margint30">Curabitur blandit tempus porttitor. Maecenas sed diam eget risus varius blandit sit amet non magna. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus nibh Curabitur blandit tempus porttitor. Maecenas sed diam eget risus varius blandit sit amet non magna. Fusce dapibus, tellus ac blandit Maecenas sed diam eget risus varius blandit sit amet non magna. Fusce dapibus, tellus ac blandit tempus.</p>

						<p>Curabitur blandit tempus porttitor. Maecenas sed diam eget risus varius blandit sit amet non magna. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus nibh Curabitur blandit tempus porttitor. Maecenas sed diam eget risus varius blandit sit amr. Maecenas sed diam eget risus varius blandit sit amet non magna. Fusce dapibus, tellus ac blandit tempus.</p>
					</div>
					<div class="col-lg-4 clearfix col-sm-4">
						<div class="room-services"><!-- Room Services -->
							<h4>SERVICES</h4>
							<ul class="room-services">
								<li><i class="fa fa-calendar"></i> CALENDAR </li>
								<li><i class="fa fa-laptop"></i> 16 MBIT WI-FI </li>
								<li><i class="fa fa-umbrella"></i> 2 BALCONIES </li>
								<li><i class="fa fa-phone"></i> 2 BEDS </li>
								<li><i class="fa fa-clock-o"></i> 7/24 SERVICE </li>
							</ul>
						</div>
						<div class="location-weather margint40"><!-- Room Weather -->
							<h4>WEATHER</h4>
							<div id="weather"></div>
						</div>
					</div>
					<div class="col-lg-12 clearfix margint40 room-single-tab"><!-- Room Tab -->
						<div class="tab-style-2 ">
							<ul class="tabbed-area tab-style-nav clearfix">
								<li class="active"><h6><a href="#tab1s">EXAMPLE TAB</a></h6></li>
								<li class=""><h6><a href="#tab2s">OTHER TABS EXAMPLE</a></h6></li>
								<li class=""><h6><a href="#tab3s">SUIT IT NOW</a></h6></li>
							</ul>
							<div class="tab-content tab-style-content">
								<div class="tab-pane fade active in" id="tab1s">
									<div class="col-lg-3 margint30">
										<img alt="Tab Image" class="img-responsive" src="/images/tab-image.jpg">
									</div>
									<div class="col-lg-9 margint30">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore nesciunt ad architecto enim dignissimos incidunt recusandae officia odit sapiente laudantium obcaecati maiores aspernatur fuga neque eum? Reiciendis sit est cum magnam quos tempore tempora esse quibusdam culpa quisquam debitis eveniet necessitatibus excepturi sed ab cumque laudantium. Fugit culpa expedita odio id temporibus laudantium sunt non nemo sapiente dolorum? Soluta incidunt debitis molestiae consectetur accusantium nulla aperiam ad repellendus quas assumenda eum fugiat commodi iusto corporis adipisci autem dolor rerum! Nulla blanditiis aut vel aperiam soluta placeat quia quae libero architecto officiis eius dolorem asperiores est illo praesentium. Sunt reprehenderit alias!
										</p>
									</div>
								</div>
								<div class="tab-pane fade" id="tab2s">
									<div class="col-lg-3 margint30">
										<img alt="Tab Image" class="img-responsive" src="/images/tab-image.jpg">
									</div>
									<div class="col-lg-9 margint30">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore nesciunt ad architecto enim dignissimos incidunt recusandae officia odit sapiente laudantium obcaecati maiores aspernatur fuga neque eum? Reiciendis sit est cum magnam quos tempore tempora esse quibusdam culpa quisquam debitis eveniet necessitatibus excepturi sed ab cumque laudantium. Fugit culpa expedita odio id temporibus laudantium sunt non nemo sapiente dolorum? Soluta incidunt debitis molestiae consectetur accusantium nulla aperiam ad repellendus quas assumenda eum fugiat commodi iusto corporis adipisci autem dolor rerum! Nulla blanditiis aut vel aperiam soluta placeat quia quae libero architecto officiis eius dolorem asperiores est illo praesentium. Sunt reprehenderit alias!
										</p>
									</div>
								</div>
								<div class="tab-pane fade" id="tab3s">
									<div class="col-lg-3 margint30">
										<img alt="Tab Image" class="img-responsive" src="/images/tab-image.jpg">
									</div>
									<div class="col-lg-9 margint30">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore nesciunt ad architecto enim dignissimos incidunt recusandae officia odit sapiente laudantium obcaecati maiores aspernatur fuga neque eum? Reiciendis sit est cum magnam quos tempore tempora esse quibusdam culpa quisquam debitis eveniet necessitatibus excepturi sed ab cumque laudantium. Fugit culpa expedita odio id temporibus laudantium sunt non nemo sapiente dolorum? Soluta incidunt debitis molestiae consectetur accusantium nulla aperiam ad repellendus quas assumenda eum fugiat commodi iusto corporis adipisci autem dolor rerum! Nulla blanditiis aut vel aperiam soluta placeat quia quae libero architecto officiis eius dolorem asperiores est illo praesentium. Sunt reprehenderit alias!
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 clearfix"><!-- Sidebar -->
					<div class="quick-reservation-container">
						<div class="quick-reservation clearfix">
							<div class="title-quick pos-center margint30">
								<h5>QUICK RESERVATIONS</h5>
								<div class="line"></div>
							</div>
							<div class="reserve-form-area">
								<form action="#" method="post" id="ajax-reservation-form">
									<label>ARRIVAL</label>
									<input type="text" id="dpd1" name="dpd1" class="date-selector" placeholder="&#xf073;" />
									<label>RETURN</label>
									<input type="text" id="dpd2" name="dpd2" class="date-selector" placeholder="&#xf073;" />
									<label>FULL NAME</label>
									<input type="text" id="dpd3" name="dpd3" class="date-selector" placeholder="&#xf073;" />
									<label>PHONE NUMBER</label>
									<input type="text" id="dpd3" name="dpd3" class="date-selector" placeholder="&#xf073;" />
									<div class="pull-left children clearfix">
										<label>ROOMS</label>
										<select name="rooms" class="pretty-select">
											<option selected="selected" value="1" >1</option>
											<option value="2">2</option>
											<option value="3">3</option>
											<option value="4">4</option>
											<option value="5">5</option>
										</select>
									</div>
									<div class="pull-left type clearfix">
										<label>ADULT</label>
										<select name="adult" class="pretty-select">
											<option selected="selected" value="1" >1</option>
											<option value="2">2</option>
											<option value="3">3</option>
											<option value="4">4</option>
											<option value="5">5</option>
									</select>
									</div>
									<div class="pull-left rooms clearfix">
										<label>CHILDREN</label>
										<select name="children" class="pretty-select">
											<option selected="selected" value="0" >0</option>
											<option value="1">1</option>
											<option value="2">2</option>
											<option value="3">3</option>
											<option value="4">4</option>
											<option value="5">5</option>
										</select>
									</div>
									<div class="pull-left search-button clearfix">
										<div class="button-style-1">
											<a id="res-submit" href="#">SEARCH</a>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
					<div class="luxen-widget news-widget">
						<div class="title-quick marginb20">
							<h5>HOTEL INFORMATION</h5>
						</div>
						<p>Curabitur blandit tempus porttitor. Nulla vitae elit libero, a pharetra augue. Lorem ipsumero, a pharetra augue. Lorem ipsum dolor sit amet, consectedui.</p>
					</div>
					<div class="luxen-widget news-widget">
						<div class="title">
							<h5>CONTACT</h5>
						</div>
						<ul class="footer-links">
							<li><p><i class="fa fa-map-marker"></i> Lorem ipsum dolor sit amet lorem Victoria 8011 Australia </p></li>
							<li><p><i class="fa fa-phone"></i> +61 3 8376 6284 </p></li>
							<li><p><i class="fa fa-envelope"></i> info@2035themes.com</p></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("share/footer"); ?>
<!-- JS FILES -->
<!-- <script src="/js/hotel/vendor/jquery-1.11.1.min.js"></script> -->
<script src="/js/hotel/vendor/bootstrap.min.js"></script>
<script src="/js/hotel/retina-1.1.0.min.js"></script>
<script src="/js/hotel/jquery.flexslider-min.js"></script>
<script src="/js/hotel/superfish.pack.1.4.1.js"></script>
<script src="/js/hotel/jquery.prettyPhoto.js"></script>
<script src="/js/hotel/bootstrap-datepicker.js"></script>
<script src="/js/hotel/selectordie.min.js"></script>
<script src="/js/hotel/jquery.slicknav.min.js"></script>
<script src="/js/hotel/jquery.parallax-1.1.3.js"></script>
<script src="/js/hotel/jquery.simpleWeather.min.js"></script>
<script src="/js/hotel/main.js"></script>
</body>
</html>