<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Luxen Premium Hotel Template</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<link rel="shortcut icon" href="img/favicon.ico" />
<!-- CSS FILES -->
<link rel="stylesheet" type="text/css" href="/css/frontend/Vendor/awesome-font/font-awesome.css">
<link rel="stylesheet" href="/css/frontend/hotel/bootstrap.min.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/flexslider.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/prettyPhoto.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/datepicker.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/selectordie.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/main.css">
<link rel="stylesheet" href="/public/css/frontend/hotel/2035.responsive.css">

<script src="/js/jquery-1.12.4.min.js"></script>
<!-- Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
<![endif]-->
</head>
<body>
<!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
<div id="wrapper">
	<div class="header"><!-- Header Section -->
		<div class="main-header"><!-- Main-header -->
			<div class="container">
				<div class="row">
					<div class="pull-left">
						<div class="logo">
							<a href="index.html"><img alt="Logo" src="/images/logo.svg" class="img-responsive" width="70" height="33"/></a>
						</div>
					</div>
					<div class="pull-right">
						<div class="pull-left">
							<nav class="nav">
								<ul id="navigate" class="sf-menu navigate">
									<li class="parent-menu active"><a href="index.html">HOMEPAGE</a>
									</li>
									<li class="parent-menu"><a href="#">FEATURES</a>
									</li>
									<li class="parent-menu"><a href="#">PAGES</a>
									</li>
									<li><a href="blog.html">NEWS</a></li>
									<li><a href="contact.html">CONTACT</a></li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="slider slider-home"><!-- Slider Section -->
		<div class="flexslider slider-loading falsenav">
			<ul class="slides">
				<li>
					<div class="slider-textbox clearfix">
						<div class="container">
							<div class="row">
                    			<div class="slider-bar pull-left">WELCOME TO LUXEN PREMIUM HOTEL TEMPLATE...</div>
                    			<div class="slider-triangle pull-left"></div>
							</div>
						</div>
						<div class="container">
							<div class="row">
                    			<div class="slider-bar-under pull-left">5 STAR SUPPORT</div>
                    			<div class="slider-triangle-under pull-left"></div>
							</div>
						</div>
					</div>
					<img alt="Slider 1" class="img-responsive" src="../../../../public/images/hinh1.jpg" />
				</li>
				<li>
					<div class="slider-textbox clearfix">
						<div class="container">
							<div class="row">
                    			<div class="slider-bar pull-left">WELCOME TO LUXEN PREMIUM HOTEL TEMPLATE...</div>
                    			<div class="slider-triangle pull-left"></div>
							</div>
						</div>
						<div class="container">
							<div class="row">
                    			<div class="slider-bar-under pull-left">5 STAR SUPPORT</div>
                    			<div class="slider-triangle-under pull-left"></div>
							</div>
						</div>
					</div>
					<img alt="Slider 1" class="img-responsive" src="../../../../public/images/hinh1.jpg" />
				</li>
			</ul>
		</div>
		<div class="bottom-book-slider">
			<div class="container">
				<div class="row pos-center">
					<ul>
						<li><i class="fa fa-shopping-cart"></i> WOOCOMMERCE COMPATIBLE</li>
						<li><i class="fa fa-globe"></i> LANGUAGE COMPATIBLE</li>
						<li><i class="fa fa-coffee"></i> COFFEE & BREAKFAST FREE</li>
						<li><i class="fa fa-windows"></i> FREE WI-FI ALL ROOM</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="content"><!-- Content Section -->
		<div class="about clearfix"><!-- About Section -->
			<div class="container">
				<div class="row">
					<div class="about-title pos-center">
						<h2>WELCOME TO PARADISE</h2>
						<div class="bottom-img">
				            <img src="../../../../public/images/line.png" alt="">
				        </div>
						<p>Nullam quis risus eget urna mollis ornare vel eu leo. Cras mattis consectetur purus sit amet fermentum. Praesent <span class="active-color">commodo</span> cursus magna, vel scelerisque nisl .Nulleget urna mattis consectetur purus sit amet fermentum</p>
					</div>
					<div class="otel-info margint60">
						<div class="col-lg-4 col-sm-12">
							<div class="title-style-1 marginb40">
								<h5>GALLERY</h5>
								<hr>
							</div>
							<div class="flexslider">
								<ul class="slides">
									<li><img alt="Slider 1" class="img-responsive" src="temp/otel-info-image-1.jpg" /></li>
									<li><img alt="Slider 1" class="img-responsive" src="temp/otel-info-image-2.jpg" /></li>
								</ul>
							</div>
						</div>
						<div class="col-lg-4 col-sm-6">
							<div class="title-style-1 marginb40">
								<h5>ABOUT US</h5>
								<hr>
							</div>
							<p>Sed posuere consectetur est at lobortis. Aenean lacinia bibendum nulla sed consectetur. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget laci. Maecenas faucibus mollis interdum.</p>
							<p>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fer condimentum nibh, ut fermentum massa justo sit amet risus. mentum massa justo sit amet risus.</p>
							<p>Fusce dapibus, tellus ac cursus commodo ut fermentum massa. mentum massa justo sit amet risus.</p>
						</div>
						<div class="col-lg-4 col-sm-6">
							<div class="title-style-1 marginb40">
								<h5>OUR NEWS</h5>
								<hr>
							</div>
							<div class="home-news">
								<div class="news-box clearfix">
									<div class="news-time pull-left">
										<div class="news-date pos-center"><div class="date-day">20<hr /></div>MAY</div>
									</div>
									<div class="news-content pull-left">
										<h6><a href="#">News from us from now</a></h6>
										<p class="margint10">Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui <a class="active-color" href="#">[...]</a></p>
									</div>
								</div>
								<div class="news-box clearfix">
									<div class="news-time pull-left">
										<div class="news-date pos-center"><div class="date-day">20<hr /></div>MAY</div>
									</div>
									<div class="news-content pull-left">
										<h6><a href="#">News from us from now</a></h6>
										<p class="margint10">Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue <a class="active-color" href="#">[...]</a></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="explore-rooms margint30 clearfix"><!-- Explore Rooms Section -->
			<div class="container">
				<div class="row">	
					<div class="title-style-2 marginb40 pos-center">
						<h3>EXPLORE ROOMS</h3>
						<div class="bottom-img">
				            <img src="../../../../public/images/line.png" alt="">
				        </div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<img alt="Room Images" class="img-responsive" src="temp/room-image-1.jpg">
								<div class="home-room-details">
									<h5><a href="#">The luxury room in Istanbul</a></h5>
									<div class="pull-left">
										<ul>
											<li><i class="fa fa-calendar"></i></li>
											<li><i class="fa fa-flask"></i></li>
											<li><i class="fa fa-umbrella"></i></li>
											<li><i class="fa fa-laptop"></i></li>
										</ul>
									</div>
									<div class="pull-right room-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star inactive"></i></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<img alt="Room Images" class="img-responsive" src="temp/room-image-6.jpg">
								<div class="home-room-details">
									<h5><a href="#">The King Room</a></h5>
									<div class="pull-left">
										<ul>
											<li><i class="fa fa-calendar"></i></li>
											<li><i class="fa fa-flask"></i></li>
											<li><i class="fa fa-umbrella"></i></li>
											<li><i class="fa fa-laptop"></i></li>
										</ul>
									</div>
									<div class="pull-right room-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star inactive"></i></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<div class="room-features">FEATURED</div>
								<img alt="Room Images" class="img-responsive" src="temp/room-image-3.jpg">
								<div class="home-room-details">
									<h5><a href="#">Awesome Suits</a></h5>
									<div class="pull-left">
										<ul>
											<li><i class="fa fa-calendar"></i></li>
											<li><i class="fa fa-flask"></i></li>
											<li><i class="fa fa-umbrella"></i></li>
											<li><i class="fa fa-laptop"></i></li>
										</ul>
									</div>
									<div class="pull-right room-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star inactive"></i></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="parallax123" class="parallax parallax-one clearfix margint60"><!-- Parallax Section -->
			<div class="support-section">
				<div class="container">
					<div class="row">
						<div class="col-lg-4 col-sm-4">
							<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
								<div class="flipper">
									<div class="support-box pos-center front">
										<div class="support-box-title"><i class="fa fa-phone"></i></div>
										<h4>CALL US</h4>
										<p class="margint20">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut ferme fentum</p>
									</div>
									<div class="support-box pos-center back">
										<div class="support-box-title"><i class="fa fa-phone"></i></div>
										<h4>PHONE NUMBER</h4>
										<p class="margint20">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, et.<br />+61 3 8376 6284</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-sm-4">
							<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
								<div class="flipper">
									<div class="support-box pos-center front">
										<div class="support-box-title"><i class="fa fa-envelope"></i></div>
										<h4>SEND US E-MAIL</h4>
										<p class="margint20">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut ferme fentum</p>
									</div>
									<div class="support-box pos-center back">
										<div class="support-box-title"><i class="fa fa-envelope"></i></div>
										<h4>E-MAIL ADDRESS</h4>
										<p class="margint20">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, et.<br />luxen@2035themes.com</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-sm-4">
							<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
								<div class="flipper">
									<div class="support-box pos-center front">
										<div class="support-box-title"><i class="fa fa-home"></i></div>
										<h4>VISIT US</h4>
										<p class="margint20">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut ferme fentum</p>
									</div>
									<div class="support-box pos-center back">
										<div class="support-box-title"><i class="fa fa-home"></i></div>
										<h4>COMPANY ADDRESS</h4>
										<p class="margint20">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, et.<br />Manhattan square. 124 avenue. Bodrum</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("share/footer"); ?>
<!-- JS FILES -->
<script src="../../../../public/js/jquery-1.12.4.min.js"></script>
<script src="../../../../public/js/hotel/vendor/bootstrap.min.js"></script>
<script src="../../../../public/js/hotel/retina-1.1.0.min.js"></script>
<script src="../../../../public/js/hotel/jquery.flexslider-min.js"></script>
<script src="../../../../public/js/hotel/superfish.pack.1.4.1.js"></script>
<script src="../../../../public/js/hotel/jquery.prettyPhoto.js"></script>
<script src="../../../../public/js/hotel/bootstrap-datepicker.js"></script>
<script src="../../../../public/js/hotel/selectordie.min.js"></script>
<script src="../../../../public/js/hotel/jquery.slicknav.min.js"></script>
<script src="../../../../public/js/hotel/jquery.parallax-1.1.3.js"></script>
<script src="../../../../public/js/hotel/main.js"></script>
<!--
<script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src='//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
-->
</body>
</html>