<div id="wrapper">
	<div class="slider slider-home"><!-- Slider Section -->
		<div class="flexslider slider-loading falsenav">
			<ul class="slides">
				<?php foreach($data['sliderpic'] as $itempic):?>
				<li>
					<img alt="<?php echo $itempic->name?>" class="img-responsive" src="/<?php echo $itempic->dir?>" />
				</li>
				<?php endforeach;?>
			</ul>
		</div>
	</div>
	<div class="hotel-content"><!-- Content Section -->
		<div class="explore-rooms margint30 clearfix"><!-- Explore Rooms Section -->
			<div class="container">
				<div class="row">	
					<div class="title-style-2 marginb40 pos-center">
						<h3>LOẠI PHÒNG</h3>
						<div class="bottom-img">
				            <img src="/images/line.png" alt="">
				        </div>
					</div>
					<?php foreach($data['hotels'] as $hotel):?>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<img alt="Room Images" class="img-responsive" src="temp/room-image-1.jpg">
								<div class="home-room-details">
									<h5><a href="#"><?php echo $hotel->name?></a></h5>
								</div>
							</div>
							<div class="room-details">
								<p><?php echo $hotel->content_short?></p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4><?php echo number_format("$hotel->price") ?>đ<span class="room-bottom-time">/Đêm</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="/hotel/detail/<?php echo $hotel->slug ?>">XEM</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<?php endforeach;?>

				</div>
			</div>
		</div>
	</div>
</div>