<div id="wrapper">
	<div class="slider slider-home"><!-- Slider Section -->
		<div class="flexslider slider-loading falsenav">
			<ul class="slides">
				<li>
					<img alt="Slider 1" class="img-responsive" src="/images/hinh1.jpg" />
				</li>
				<li>
					<img alt="Slider 1" class="img-responsive" src="/images/hinh1.jpg" />
				</li>
			</ul>
		</div>
	</div>
	<div class="hotel-content"><!-- Content Section -->
		<div class="explore-rooms margint30 clearfix"><!-- Explore Rooms Section -->
			<div class="container">
				<div class="row">	
					<div class="title-style-2 marginb40 pos-center">
						<h3>EXPLORE ROOMS</h3>
						<div class="bottom-img">
				            <img src="/images/line.png" alt="">
				        </div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<img alt="Room Images" class="img-responsive" src="temp/room-image-1.jpg">
								<div class="home-room-details">
									<h5><a href="#">The luxury room in Istanbul</a></h5>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<img alt="Room Images" class="img-responsive" src="temp/room-image-6.jpg">
								<div class="home-room-details">
									<h5><a href="#">The King Room</a></h5>
									<div class="pull-left">
										<ul>
											<li><i class="fa fa-calendar"></i></li>
											<li><i class="fa fa-flask"></i></li>
											<li><i class="fa fa-umbrella"></i></li>
											<li><i class="fa fa-laptop"></i></li>
										</ul>
									</div>
									<div class="pull-right room-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star inactive"></i></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-6">
						<div class="home-room-box">
							<div class="room-image">
								<div class="room-features">FEATURED</div>
								<img alt="Room Images" class="img-responsive" src="temp/room-image-3.jpg">
								<div class="home-room-details">
									<h5><a href="#">Awesome Suits</a></h5>
									<div class="pull-left">
										<ul>
											<li><i class="fa fa-calendar"></i></li>
											<li><i class="fa fa-flask"></i></li>
											<li><i class="fa fa-umbrella"></i></li>
											<li><i class="fa fa-laptop"></i></li>
										</ul>
									</div>
									<div class="pull-right room-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star inactive"></i></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="room-details">
								<p>Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Curabitur blandit tibulum at ero[...]</p>
							</div>
							<div class="room-bottom">
								<div class="pull-left"><h4>89$<span class="room-bottom-time">/ Day</span></h4></div>
								<div class="pull-right">
									<div class="button-style-1">
										<a href="#">BOOK NOW</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>